# -*- coding: utf-8 -*-
"""week1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KeZekzFCxZck-1w806Rv33FGSSByLFc
"""

# ==========================================================
# WEEK 1 - DATASET EXPLORATION
# ==========================================================

import pandas as pd


# ==========================================================
# 1. LOAD DATASET
# ==========================================================

CSV_PATH = "placement_predict_50k.csv"

try:

    df = pd.read_csv(CSV_PATH)

    # Remove extra spaces from column names
    df.columns = df.columns.str.strip()

    print("Dataset loaded successfully!")
    print("=" * 60)


    # ======================================================
    # 2. DISPLAY FIRST 5 ROWS
    # ======================================================

    print("\nFIRST 5 ROWS")
    print("=" * 60)

    display(df.head())


    # ======================================================
    # 3. DISPLAY DATASET SHAPE
    # ======================================================

    print("\nDATASET SHAPE")
    print("=" * 60)

    print("Rows    :", df.shape[0])
    print("Columns :", df.shape[1])


    # ======================================================
    # 4. DISPLAY COLUMN NAMES
    # ======================================================

    print("\nCOLUMN NAMES")
    print("=" * 60)

    for i, column in enumerate(df.columns, start=1):
        print(f"{i}. {column}")


    # ======================================================
    # 5. DISPLAY DATA TYPES
    # ======================================================

    print("\nDATA TYPES")
    print("=" * 60)

    print(df.dtypes)


    # ======================================================
    # 6. DISPLAY DATASET INFORMATION
    # ======================================================

    print("\nDATASET INFORMATION")
    print("=" * 60)

    df.info()


    # ======================================================
    # 7. DISPLAY STATISTICAL SUMMARY
    # ======================================================

    print("\nSTATISTICAL SUMMARY")
    print("=" * 60)

    display(df.describe(include="all"))


    # ======================================================
    # 8. CHECK MISSING VALUES
    # ======================================================

    print("\nMISSING VALUES")
    print("=" * 60)

    missing_values = df.isnull().sum()

    print(missing_values)


    # ======================================================
    # 9. CHECK DUPLICATE ROWS
    # ======================================================

    print("\nDUPLICATE ROWS")
    print("=" * 60)

    duplicate_count = df.duplicated().sum()

    print("Number of duplicate rows:", duplicate_count)


    # ======================================================
    # 10. PLACEMENT STATUS DISTRIBUTION
    # ======================================================

    print("\nPLACEMENT STATUS DISTRIBUTION")
    print("=" * 60)

    if "PlacementStatus" in df.columns:

        print(
            df["PlacementStatus"].value_counts()
        )

    else:

        print("Column 'PlacementStatus' not found.")


    # ======================================================
    # 11. PLACEMENT STATUS PERCENTAGE
    # ======================================================

    print("\nPLACEMENT STATUS PERCENTAGE")
    print("=" * 60)

    if "PlacementStatus" in df.columns:

        percentage = (
            df["PlacementStatus"]
            .value_counts(normalize=True)
            * 100
        )

        print(percentage.round(2))

    else:

        print("Column 'PlacementStatus' not found.")


    # ======================================================
    # 12. FINAL SUMMARY
    # ======================================================

    print("\n" + "=" * 60)
    print("WEEK 1 ANALYSIS COMPLETED SUCCESSFULLY!")
    print("=" * 60)


except FileNotFoundError:

    print(
        "ERROR: placement_predict_50k.csv was not found."
    )

    print(
        "Please upload the CSV file using:"
    )

    print(
        "from google.colab import files"
    )

except Exception as e:

    print("ERROR:", e)