# -*- coding: utf-8 -*-
"""week2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHYaLQhdiBS7Bt4guV9txIf_hHxAveeu
"""

# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages

# ==========================================================
# 1. LOAD DATASET
# ==========================================================

df = pd.read_csv("/content/placement_predict_50k.csv")

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)
print(df.head())


# ==========================================================
# 2. SET SEABORN STYLE
# ==========================================================

sns.set_style("whitegrid")


# ==========================================================
# 3. MISSINGNESS HEATMAP
# ==========================================================

fig1 = plt.figure(figsize=(10, 6))

sns.heatmap(
    df.isnull(),
    cbar=False,
    cmap="viridis",
    yticklabels=False
)

plt.title("Missingness Heatmap - Placement Prediction Dataset")
plt.xlabel("Columns")
plt.ylabel("Rows")
plt.tight_layout()
plt.show()


# ==========================================================
# 4. SELECT NUMERICAL COLUMNS
# ==========================================================

num_cols = df.select_dtypes(include=np.number).columns

print("\nNumerical columns:")
print(list(num_cols))


# ==========================================================
# 5. HISTOGRAMS OF NUMERICAL FEATURES
# ==========================================================

n_features = min(6, len(num_cols))

fig2, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i in range(n_features):

    feature = num_cols[i]

    sns.histplot(
        df[feature].dropna(),
        bins=30,
        kde=True,
        ax=axes[i]
    )

    axes[i].set_title(f"Distribution of {feature}")
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel("Frequency")


# Hide unused subplots
for i in range(n_features, 6):
    axes[i].set_visible(False)

plt.tight_layout()
plt.show()


# ==========================================================
# 6. PAIRPLOT
# ==========================================================

pair_cols = num_cols[:4]

# Use maximum 5000 rows so Colab doesn't become slow
pair_data = df[pair_cols].dropna()

if len(pair_data) > 5000:
    pair_data = pair_data.sample(
        5000,
        random_state=42
    )

fig3 = sns.pairplot(pair_data)

fig3.fig.suptitle(
    "Pairplot of Numerical Features",
    y=1.02
)

plt.show()


# ==========================================================
# 7. CORRELATION HEATMAP
# ==========================================================

fig4 = plt.figure(figsize=(10, 8))

numeric_df = df.select_dtypes(include=np.number)

corr_matrix = numeric_df.corr()

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    square=True,
    linewidths=0.5
)

plt.title("Correlation Heatmap - Numerical Features")
plt.tight_layout()
plt.show()


# ==========================================================
# 8. BOXPLOTS
# ==========================================================

fig5, axes5 = plt.subplots(2, 3, figsize=(15, 8))
axes5 = axes5.flatten()

for i in range(n_features):

    feature = num_cols[i]

    sns.boxplot(
        y=df[feature],
        ax=axes5[i]
    )

    axes5[i].set_title(f"Boxplot of {feature}")
    axes5[i].set_ylabel(feature)


# Hide unused subplots
for i in range(n_features, 6):
    axes5[i].set_visible(False)

plt.tight_layout()
plt.show()


# ==========================================================
# 9. CREATE PDF REPORT
# ==========================================================

with PdfPages("EDA_Report.pdf") as pdf:

    pdf.savefig(fig1)
    pdf.savefig(fig2)
    pdf.savefig(fig3.fig)
    pdf.savefig(fig4)
    pdf.savefig(fig5)


print("EDA_Report.pdf has been created successfully!")


# ==========================================================
# 10. DOWNLOAD PDF
# ==========================================================

from google.colab import files

files.download("EDA_Report.pdf")